<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChamadoMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadoMessageRepository extends EntityRepository
{
  /**
   * Adiciona filtros para selecionar apenas registros ativos à query.
   * @param QueryBuilder $qb Query inicial.
   * @return QueryBuilder Query com filtros.
   */
  public function addActiveQuery(QueryBuilder $qb = null) {
      $em = $this->getEntityManager();

      if (is_null($qb)) {
          $qb = $em->createQueryBuilder();
      }

      $qb->select(array('cm'))
          ->from('AppBundle:ChamadoMessage', 'cm');

      return $qb;
  }

  /**
   * Busca de usuários do tipo user
   * @return QueryResult
   */
  public function findByChamado($chamado)
  {
      $qb = $this->addActiveQuery();

      $qb->andWhere('cm.chamado = :chamado')
          ->setParameter('chamado', $chamado);
      $qb->orderBy("cm.dtCreation","DESC");

      $query = $qb->getQuery();

      return $query->getResult();
  }

}
