<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SLARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SLARepository extends EntityRepository
{

  /**
   * Adiciona filtros para selecionar apenas registros ativos à query.
   * @param QueryBuilder $qb Query inicial.
   * @return QueryBuilder Query com filtros.
   */
  public function addActiveQuery(QueryBuilder $qb = null) {
    $em = $this->getEntityManager();

    if (is_null($qb)) {
      $qb = $em->createQueryBuilder();
    }

    $qb->select(array('s'))
    ->from('AppBundle:SLA', 's');

    return $qb;
  }

  /**
   * Busca de sla por item e tipo de atendimento
   * @return QueryResult
   */
  public function findOneByItemAttendance($item, $attendance)
  {
    $qb = $this->addActiveQuery();
    $qb->setMaxResults(1);
    $qb->andWhere('s.item = :item')
    ->setParameter('item', $item);

    $qb->andWhere('s.attendance = :attendance')
    ->setParameter('attendance', $attendance);

    $query = $qb->getQuery();

    return $query->getOneOrNullResult();
  }

}
